name: i69n
description: Simple internationalization tool for Dart and Flutter, based on YAML files and source code generation.
version: 1.2.0
homepage: https://github.com/fnx-io/i69n

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  build: ^1.6.3
  build_config: ^0.4.6
  yaml: ^3.1.0
  dart_style: ">=1.2.0 <2.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  build_runner: ^1.11.5
  build_web_compilers: ^2.16.4
